# Generated by Django 4.0.5 on 2022-06-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('idAutor', models.IntegerField(primary_key=True, serialize=False, verbose_name='id Autor')),
                ('pnombreAutor', models.CharField(max_length=60, verbose_name='Primer nombre')),
                ('appaternoAutor', models.CharField(max_length=60, verbose_name='Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('anhio_nac', models.IntegerField(verbose_name='Fecha nacimiento')),
                ('pais', models.CharField(max_length=60, verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pinturas',
            fields=[
                ('idPintura', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='idPintura')),
                ('nombre_pintura', models.CharField(max_length=20, verbose_name='Nombre Pintura')),
                ('precio_pintura', models.IntegerField(blank=True, null=True, verbose_name='Precio')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
        migrations.DeleteModel(
            name='Pintura',
        ),
    ]
